export const ADICIONAR_UM = 'ADICIONAR_UM',
            GET_CLIENTES = 'GET_CLIENTES',
            ADD_CLIENTE = 'ADD_CLIENTE',
            UPDATE_CLIENTE = 'UPDATE_CLIENTE',
            REMOVE_CLIENTE = 'REMOVE_CLIENTE',
            SET_ORDENACAO = 'SET_ORDENACAO',
            SET_PESQUISA = 'SET_PESQUISA',
            GET_TRANSACTIONS = 'GET_TRANSACTIONS';