export const ADICIONAR_UM = 'ADICIONAR_UM',
            GET_CLIENTES = 'GET_CLIENTES',
            ADD_CLIENTE = 'ADD_CLIENTE',
            UPDATE_CLIENTE = 'UPDATE_CLIENTE',
            REMOVE_CLIENTE = 'REMOVE_CLIENTE';